"""Numeric constants that control game behaviour and screen dimensions."""

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5

HUD_FONT_SIZE = 36
HUD_MARGIN = 10

PLAYER_MAX_HP = 10
PLAYER_HP_DAMAGE_LARGE = 3
PLAYER_HP_DAMAGE_SMALL = 1
PLAYER_INVINCIBILITY_DURATION = 1.5
